Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -79,12 +79,20 @@ jobs:
     # Check and Install PM2 if not present
     - name: Check and Install PM2
       run: |
-        if ! command -v pm2 &> /dev/null; then
-          echo "PM2 not found. Installing..."
-          sudo npm i -g pm2
+        # if ! command -v pm2 &> /dev/null; then
+        #   echo "PM2 not found. Installing..."
+        #   sudo npm i -g pm2
+        # else
+        #   echo "PM2 is already installed"
+        #   pm2 --version
+        # fi
+
+        if pm2 describe server > /dev/null 2>&1; then
+          echo "Server process exists, restarting..."
+          pm2 restart server
         else
-          echo "PM2 is already installed"
-          pm2 --version
+          echo "Server process not found, starting new instance..."
+          pm2 start server.js --name server
         fi
     
     # Application build steps
